/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PontoRouteImport } from './routes/ponto'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalFotosRouteImport } from './routes/portal/fotos'
import { Route as PortalFinanceiroRouteImport } from './routes/portal/financeiro'
import { Route as PortalDocumentosRouteImport } from './routes/portal/documentos'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppRhRouteImport } from './routes/_app/rh'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppOrcamentosRouteImport } from './routes/_app/orcamentos'
import { Route as AppObrasRouteImport } from './routes/_app/obras'
import { Route as AppMedicoesRouteImport } from './routes/_app/medicoes'
import { Route as AppImportacoesRouteImport } from './routes/_app/importacoes'
import { Route as AppImobiliariaRouteImport } from './routes/_app/imobiliaria'
import { Route as AppFiscalRouteImport } from './routes/_app/fiscal'
import { Route as AppFinanceiroRouteImport } from './routes/_app/financeiro'
import { Route as AppEstoqueRouteImport } from './routes/_app/estoque'
import { Route as AppEquipamentosRouteImport } from './routes/_app/equipamentos'
import { Route as AppEmpresaRouteImport } from './routes/_app/empresa'
import { Route as AppDocumentosRouteImport } from './routes/_app/documentos'
import { Route as AppDiarioRouteImport } from './routes/_app/diario'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCronogramaRouteImport } from './routes/_app/cronograma'
import { Route as AppComprasRouteImport } from './routes/_app/compras'
import { Route as AppComercialRouteImport } from './routes/_app/comercial'
import { Route as AppVendasPedidosRouteImport } from './routes/_app/vendas.pedidos'
import { Route as AppImobiliariaLocacoesRouteImport } from './routes/_app/imobiliaria.locacoes'
import { Route as AppImobiliariaImoveisRouteImport } from './routes/_app/imobiliaria.imoveis'
import { Route as AppImobiliariaFinanceiroRouteImport } from './routes/_app/imobiliaria.financeiro'
import { Route as AppImobiliariaFiadoresRouteImport } from './routes/_app/imobiliaria/fiadores'
import { Route as AppImobiliariaDashboardRouteImport } from './routes/_app/imobiliaria.dashboard'
import { Route as AppImobiliariaClientesRouteImport } from './routes/_app/imobiliaria.clientes'
import { Route as AppComercialPropostasRouteImport } from './routes/_app/comercial.propostas'
import { Route as AppComercialOportunidadesRouteImport } from './routes/_app/comercial.oportunidades'
import { Route as AppComercialLicitacoesRouteImport } from './routes/_app/comercial.licitacoes'
import { Route as AppComercialContratosRouteImport } from './routes/_app/comercial.contratos'
import { Route as AppComercialClientesRouteImport } from './routes/_app/comercial.clientes'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoRoute = PontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFotosRoute = PortalFotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFinanceiroRoute = PortalFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentosRoute = PortalDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => PortalRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRhRoute = AppRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppObrasRoute = AppObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicoesRoute = AppMedicoesRouteImport.update({
  id: '/medicoes',
  path: '/medicoes',
  getParentRoute: () => AppRoute,
} as any)
const AppImportacoesRoute = AppImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppImobiliariaRoute = AppImobiliariaRouteImport.update({
  id: '/imobiliaria',
  path: '/imobiliaria',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalRoute = AppFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipamentosRoute = AppEquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresaRoute = AppEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDiarioRoute = AppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCronogramaRoute = AppCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)
const AppComercialRoute = AppComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasPedidosRoute = AppVendasPedidosRouteImport.update({
  id: '/vendas/pedidos',
  path: '/vendas/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppImobiliariaLocacoesRoute = AppImobiliariaLocacoesRouteImport.update({
  id: '/locacoes',
  path: '/locacoes',
  getParentRoute: () => AppImobiliariaRoute,
} as any)
const AppImobiliariaImoveisRoute = AppImobiliariaImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AppImobiliariaRoute,
} as any)
const AppImobiliariaFinanceiroRoute =
  AppImobiliariaFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AppImobiliariaRoute,
  } as any)
const AppImobiliariaFiadoresRoute = AppImobiliariaFiadoresRouteImport.update({
  id: '/fiadores',
  path: '/fiadores',
  getParentRoute: () => AppImobiliariaRoute,
} as any)
const AppImobiliariaDashboardRoute = AppImobiliariaDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppImobiliariaRoute,
} as any)
const AppImobiliariaClientesRoute = AppImobiliariaClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppImobiliariaRoute,
} as any)
const AppComercialPropostasRoute = AppComercialPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppComercialRoute,
} as any)
const AppComercialOportunidadesRoute =
  AppComercialOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AppComercialRoute,
  } as any)
const AppComercialLicitacoesRoute = AppComercialLicitacoesRouteImport.update({
  id: '/licitacoes',
  path: '/licitacoes',
  getParentRoute: () => AppComercialRoute,
} as any)
const AppComercialContratosRoute = AppComercialContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppComercialRoute,
} as any)
const AppComercialClientesRoute = AppComercialClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppComercialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ponto': typeof PontoRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/comercial': typeof AppComercialRouteWithChildren
  '/compras': typeof AppComprasRoute
  '/cronograma': typeof AppCronogramaRoute
  '/dashboard': typeof AppDashboardRoute
  '/diario': typeof AppDiarioRoute
  '/documentos': typeof AppDocumentosRoute
  '/empresa': typeof AppEmpresaRoute
  '/equipamentos': typeof AppEquipamentosRoute
  '/estoque': typeof AppEstoqueRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/fiscal': typeof AppFiscalRoute
  '/imobiliaria': typeof AppImobiliariaRouteWithChildren
  '/importacoes': typeof AppImportacoesRoute
  '/medicoes': typeof AppMedicoesRoute
  '/obras': typeof AppObrasRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/perfil': typeof AppPerfilRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/rh': typeof AppRhRoute
  '/usuarios': typeof AppUsuariosRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/fotos': typeof PortalFotosRoute
  '/portal/': typeof PortalIndexRoute
  '/comercial/clientes': typeof AppComercialClientesRoute
  '/comercial/contratos': typeof AppComercialContratosRoute
  '/comercial/licitacoes': typeof AppComercialLicitacoesRoute
  '/comercial/oportunidades': typeof AppComercialOportunidadesRoute
  '/comercial/propostas': typeof AppComercialPropostasRoute
  '/imobiliaria/clientes': typeof AppImobiliariaClientesRoute
  '/imobiliaria/dashboard': typeof AppImobiliariaDashboardRoute
  '/imobiliaria/fiadores': typeof AppImobiliariaFiadoresRoute
  '/imobiliaria/financeiro': typeof AppImobiliariaFinanceiroRoute
  '/imobiliaria/imoveis': typeof AppImobiliariaImoveisRoute
  '/imobiliaria/locacoes': typeof AppImobiliariaLocacoesRoute
  '/vendas/pedidos': typeof AppVendasPedidosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ponto': typeof PontoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/comercial': typeof AppComercialRouteWithChildren
  '/compras': typeof AppComprasRoute
  '/cronograma': typeof AppCronogramaRoute
  '/dashboard': typeof AppDashboardRoute
  '/diario': typeof AppDiarioRoute
  '/documentos': typeof AppDocumentosRoute
  '/empresa': typeof AppEmpresaRoute
  '/equipamentos': typeof AppEquipamentosRoute
  '/estoque': typeof AppEstoqueRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/fiscal': typeof AppFiscalRoute
  '/imobiliaria': typeof AppImobiliariaRouteWithChildren
  '/importacoes': typeof AppImportacoesRoute
  '/medicoes': typeof AppMedicoesRoute
  '/obras': typeof AppObrasRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/perfil': typeof AppPerfilRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/rh': typeof AppRhRoute
  '/usuarios': typeof AppUsuariosRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/fotos': typeof PortalFotosRoute
  '/portal': typeof PortalIndexRoute
  '/comercial/clientes': typeof AppComercialClientesRoute
  '/comercial/contratos': typeof AppComercialContratosRoute
  '/comercial/licitacoes': typeof AppComercialLicitacoesRoute
  '/comercial/oportunidades': typeof AppComercialOportunidadesRoute
  '/comercial/propostas': typeof AppComercialPropostasRoute
  '/imobiliaria/clientes': typeof AppImobiliariaClientesRoute
  '/imobiliaria/dashboard': typeof AppImobiliariaDashboardRoute
  '/imobiliaria/fiadores': typeof AppImobiliariaFiadoresRoute
  '/imobiliaria/financeiro': typeof AppImobiliariaFinanceiroRoute
  '/imobiliaria/imoveis': typeof AppImobiliariaImoveisRoute
  '/imobiliaria/locacoes': typeof AppImobiliariaLocacoesRoute
  '/vendas/pedidos': typeof AppVendasPedidosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ponto': typeof PontoRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_app/comercial': typeof AppComercialRouteWithChildren
  '/_app/compras': typeof AppComprasRoute
  '/_app/cronograma': typeof AppCronogramaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/diario': typeof AppDiarioRoute
  '/_app/documentos': typeof AppDocumentosRoute
  '/_app/empresa': typeof AppEmpresaRoute
  '/_app/equipamentos': typeof AppEquipamentosRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/fiscal': typeof AppFiscalRoute
  '/_app/imobiliaria': typeof AppImobiliariaRouteWithChildren
  '/_app/importacoes': typeof AppImportacoesRoute
  '/_app/medicoes': typeof AppMedicoesRoute
  '/_app/obras': typeof AppObrasRoute
  '/_app/orcamentos': typeof AppOrcamentosRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/rh': typeof AppRhRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/financeiro': typeof PortalFinanceiroRoute
  '/portal/fotos': typeof PortalFotosRoute
  '/portal/': typeof PortalIndexRoute
  '/_app/comercial/clientes': typeof AppComercialClientesRoute
  '/_app/comercial/contratos': typeof AppComercialContratosRoute
  '/_app/comercial/licitacoes': typeof AppComercialLicitacoesRoute
  '/_app/comercial/oportunidades': typeof AppComercialOportunidadesRoute
  '/_app/comercial/propostas': typeof AppComercialPropostasRoute
  '/_app/imobiliaria/clientes': typeof AppImobiliariaClientesRoute
  '/_app/imobiliaria/dashboard': typeof AppImobiliariaDashboardRoute
  '/_app/imobiliaria/fiadores': typeof AppImobiliariaFiadoresRoute
  '/_app/imobiliaria/financeiro': typeof AppImobiliariaFinanceiroRoute
  '/_app/imobiliaria/imoveis': typeof AppImobiliariaImoveisRoute
  '/_app/imobiliaria/locacoes': typeof AppImobiliariaLocacoesRoute
  '/_app/vendas/pedidos': typeof AppVendasPedidosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/ponto'
    | '/portal'
    | '/reset-password'
    | '/comercial'
    | '/compras'
    | '/cronograma'
    | '/dashboard'
    | '/diario'
    | '/documentos'
    | '/empresa'
    | '/equipamentos'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/imobiliaria'
    | '/importacoes'
    | '/medicoes'
    | '/obras'
    | '/orcamentos'
    | '/perfil'
    | '/relatorios'
    | '/rh'
    | '/usuarios'
    | '/portal/documentos'
    | '/portal/financeiro'
    | '/portal/fotos'
    | '/portal/'
    | '/comercial/clientes'
    | '/comercial/contratos'
    | '/comercial/licitacoes'
    | '/comercial/oportunidades'
    | '/comercial/propostas'
    | '/imobiliaria/clientes'
    | '/imobiliaria/dashboard'
    | '/imobiliaria/fiadores'
    | '/imobiliaria/financeiro'
    | '/imobiliaria/imoveis'
    | '/imobiliaria/locacoes'
    | '/vendas/pedidos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/ponto'
    | '/reset-password'
    | '/comercial'
    | '/compras'
    | '/cronograma'
    | '/dashboard'
    | '/diario'
    | '/documentos'
    | '/empresa'
    | '/equipamentos'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/imobiliaria'
    | '/importacoes'
    | '/medicoes'
    | '/obras'
    | '/orcamentos'
    | '/perfil'
    | '/relatorios'
    | '/rh'
    | '/usuarios'
    | '/portal/documentos'
    | '/portal/financeiro'
    | '/portal/fotos'
    | '/portal'
    | '/comercial/clientes'
    | '/comercial/contratos'
    | '/comercial/licitacoes'
    | '/comercial/oportunidades'
    | '/comercial/propostas'
    | '/imobiliaria/clientes'
    | '/imobiliaria/dashboard'
    | '/imobiliaria/fiadores'
    | '/imobiliaria/financeiro'
    | '/imobiliaria/imoveis'
    | '/imobiliaria/locacoes'
    | '/vendas/pedidos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/forgot-password'
    | '/ponto'
    | '/portal'
    | '/reset-password'
    | '/_app/comercial'
    | '/_app/compras'
    | '/_app/cronograma'
    | '/_app/dashboard'
    | '/_app/diario'
    | '/_app/documentos'
    | '/_app/empresa'
    | '/_app/equipamentos'
    | '/_app/estoque'
    | '/_app/financeiro'
    | '/_app/fiscal'
    | '/_app/imobiliaria'
    | '/_app/importacoes'
    | '/_app/medicoes'
    | '/_app/obras'
    | '/_app/orcamentos'
    | '/_app/perfil'
    | '/_app/relatorios'
    | '/_app/rh'
    | '/_app/usuarios'
    | '/portal/documentos'
    | '/portal/financeiro'
    | '/portal/fotos'
    | '/portal/'
    | '/_app/comercial/clientes'
    | '/_app/comercial/contratos'
    | '/_app/comercial/licitacoes'
    | '/_app/comercial/oportunidades'
    | '/_app/comercial/propostas'
    | '/_app/imobiliaria/clientes'
    | '/_app/imobiliaria/dashboard'
    | '/_app/imobiliaria/fiadores'
    | '/_app/imobiliaria/financeiro'
    | '/_app/imobiliaria/imoveis'
    | '/_app/imobiliaria/locacoes'
    | '/_app/vendas/pedidos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PontoRoute: typeof PontoRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto': {
      id: '/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof PontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/fotos': {
      id: '/portal/fotos'
      path: '/fotos'
      fullPath: '/portal/fotos'
      preLoaderRoute: typeof PortalFotosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/financeiro': {
      id: '/portal/financeiro'
      path: '/financeiro'
      fullPath: '/portal/financeiro'
      preLoaderRoute: typeof PortalFinanceiroRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documentos': {
      id: '/portal/documentos'
      path: '/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof PortalDocumentosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rh': {
      id: '/_app/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AppRhRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos': {
      id: '/_app/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obras': {
      id: '/_app/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof AppObrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medicoes': {
      id: '/_app/medicoes'
      path: '/medicoes'
      fullPath: '/medicoes'
      preLoaderRoute: typeof AppMedicoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importacoes': {
      id: '/_app/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof AppImportacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imobiliaria': {
      id: '/_app/imobiliaria'
      path: '/imobiliaria'
      fullPath: '/imobiliaria'
      preLoaderRoute: typeof AppImobiliariaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal': {
      id: '/_app/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof AppFiscalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipamentos': {
      id: '/_app/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof AppEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresa': {
      id: '/_app/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AppEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos': {
      id: '/_app/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diario': {
      id: '/_app/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AppDiarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cronograma': {
      id: '/_app/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AppCronogramaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compras': {
      id: '/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comercial': {
      id: '/_app/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AppComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/pedidos': {
      id: '/_app/vendas/pedidos'
      path: '/vendas/pedidos'
      fullPath: '/vendas/pedidos'
      preLoaderRoute: typeof AppVendasPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imobiliaria/locacoes': {
      id: '/_app/imobiliaria/locacoes'
      path: '/locacoes'
      fullPath: '/imobiliaria/locacoes'
      preLoaderRoute: typeof AppImobiliariaLocacoesRouteImport
      parentRoute: typeof AppImobiliariaRoute
    }
    '/_app/imobiliaria/imoveis': {
      id: '/_app/imobiliaria/imoveis'
      path: '/imoveis'
      fullPath: '/imobiliaria/imoveis'
      preLoaderRoute: typeof AppImobiliariaImoveisRouteImport
      parentRoute: typeof AppImobiliariaRoute
    }
    '/_app/imobiliaria/financeiro': {
      id: '/_app/imobiliaria/financeiro'
      path: '/financeiro'
      fullPath: '/imobiliaria/financeiro'
      preLoaderRoute: typeof AppImobiliariaFinanceiroRouteImport
      parentRoute: typeof AppImobiliariaRoute
    }
    '/_app/imobiliaria/fiadores': {
      id: '/_app/imobiliaria/fiadores'
      path: '/fiadores'
      fullPath: '/imobiliaria/fiadores'
      preLoaderRoute: typeof AppImobiliariaFiadoresRouteImport
      parentRoute: typeof AppImobiliariaRoute
    }
    '/_app/imobiliaria/dashboard': {
      id: '/_app/imobiliaria/dashboard'
      path: '/dashboard'
      fullPath: '/imobiliaria/dashboard'
      preLoaderRoute: typeof AppImobiliariaDashboardRouteImport
      parentRoute: typeof AppImobiliariaRoute
    }
    '/_app/imobiliaria/clientes': {
      id: '/_app/imobiliaria/clientes'
      path: '/clientes'
      fullPath: '/imobiliaria/clientes'
      preLoaderRoute: typeof AppImobiliariaClientesRouteImport
      parentRoute: typeof AppImobiliariaRoute
    }
    '/_app/comercial/propostas': {
      id: '/_app/comercial/propostas'
      path: '/propostas'
      fullPath: '/comercial/propostas'
      preLoaderRoute: typeof AppComercialPropostasRouteImport
      parentRoute: typeof AppComercialRoute
    }
    '/_app/comercial/oportunidades': {
      id: '/_app/comercial/oportunidades'
      path: '/oportunidades'
      fullPath: '/comercial/oportunidades'
      preLoaderRoute: typeof AppComercialOportunidadesRouteImport
      parentRoute: typeof AppComercialRoute
    }
    '/_app/comercial/licitacoes': {
      id: '/_app/comercial/licitacoes'
      path: '/licitacoes'
      fullPath: '/comercial/licitacoes'
      preLoaderRoute: typeof AppComercialLicitacoesRouteImport
      parentRoute: typeof AppComercialRoute
    }
    '/_app/comercial/contratos': {
      id: '/_app/comercial/contratos'
      path: '/contratos'
      fullPath: '/comercial/contratos'
      preLoaderRoute: typeof AppComercialContratosRouteImport
      parentRoute: typeof AppComercialRoute
    }
    '/_app/comercial/clientes': {
      id: '/_app/comercial/clientes'
      path: '/clientes'
      fullPath: '/comercial/clientes'
      preLoaderRoute: typeof AppComercialClientesRouteImport
      parentRoute: typeof AppComercialRoute
    }
  }
}

interface AppComercialRouteChildren {
  AppComercialClientesRoute: typeof AppComercialClientesRoute
  AppComercialContratosRoute: typeof AppComercialContratosRoute
  AppComercialLicitacoesRoute: typeof AppComercialLicitacoesRoute
  AppComercialOportunidadesRoute: typeof AppComercialOportunidadesRoute
  AppComercialPropostasRoute: typeof AppComercialPropostasRoute
}

const AppComercialRouteChildren: AppComercialRouteChildren = {
  AppComercialClientesRoute: AppComercialClientesRoute,
  AppComercialContratosRoute: AppComercialContratosRoute,
  AppComercialLicitacoesRoute: AppComercialLicitacoesRoute,
  AppComercialOportunidadesRoute: AppComercialOportunidadesRoute,
  AppComercialPropostasRoute: AppComercialPropostasRoute,
}

const AppComercialRouteWithChildren = AppComercialRoute._addFileChildren(
  AppComercialRouteChildren,
)

interface AppImobiliariaRouteChildren {
  AppImobiliariaClientesRoute: typeof AppImobiliariaClientesRoute
  AppImobiliariaDashboardRoute: typeof AppImobiliariaDashboardRoute
  AppImobiliariaFiadoresRoute: typeof AppImobiliariaFiadoresRoute
  AppImobiliariaFinanceiroRoute: typeof AppImobiliariaFinanceiroRoute
  AppImobiliariaImoveisRoute: typeof AppImobiliariaImoveisRoute
  AppImobiliariaLocacoesRoute: typeof AppImobiliariaLocacoesRoute
}

const AppImobiliariaRouteChildren: AppImobiliariaRouteChildren = {
  AppImobiliariaClientesRoute: AppImobiliariaClientesRoute,
  AppImobiliariaDashboardRoute: AppImobiliariaDashboardRoute,
  AppImobiliariaFiadoresRoute: AppImobiliariaFiadoresRoute,
  AppImobiliariaFinanceiroRoute: AppImobiliariaFinanceiroRoute,
  AppImobiliariaImoveisRoute: AppImobiliariaImoveisRoute,
  AppImobiliariaLocacoesRoute: AppImobiliariaLocacoesRoute,
}

const AppImobiliariaRouteWithChildren = AppImobiliariaRoute._addFileChildren(
  AppImobiliariaRouteChildren,
)

interface AppRouteChildren {
  AppComercialRoute: typeof AppComercialRouteWithChildren
  AppComprasRoute: typeof AppComprasRoute
  AppCronogramaRoute: typeof AppCronogramaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiarioRoute: typeof AppDiarioRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEmpresaRoute: typeof AppEmpresaRoute
  AppEquipamentosRoute: typeof AppEquipamentosRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFiscalRoute: typeof AppFiscalRoute
  AppImobiliariaRoute: typeof AppImobiliariaRouteWithChildren
  AppImportacoesRoute: typeof AppImportacoesRoute
  AppMedicoesRoute: typeof AppMedicoesRoute
  AppObrasRoute: typeof AppObrasRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppRhRoute: typeof AppRhRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVendasPedidosRoute: typeof AppVendasPedidosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComercialRoute: AppComercialRouteWithChildren,
  AppComprasRoute: AppComprasRoute,
  AppCronogramaRoute: AppCronogramaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiarioRoute: AppDiarioRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppEmpresaRoute: AppEmpresaRoute,
  AppEquipamentosRoute: AppEquipamentosRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFiscalRoute: AppFiscalRoute,
  AppImobiliariaRoute: AppImobiliariaRouteWithChildren,
  AppImportacoesRoute: AppImportacoesRoute,
  AppMedicoesRoute: AppMedicoesRoute,
  AppObrasRoute: AppObrasRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppRhRoute: AppRhRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVendasPedidosRoute: AppVendasPedidosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalDocumentosRoute: typeof PortalDocumentosRoute
  PortalFinanceiroRoute: typeof PortalFinanceiroRoute
  PortalFotosRoute: typeof PortalFotosRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDocumentosRoute: PortalDocumentosRoute,
  PortalFinanceiroRoute: PortalFinanceiroRoute,
  PortalFotosRoute: PortalFotosRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PontoRoute: PontoRoute,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
